### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by gokulkrishh** [gokulkrishh/anonymous-web#1]
- [x] Add custom domain name
- [x] Add SSL certificate - in progress
- [x] Configure cloudflare settings
- [x] Add google analytics
